### ISSUE TITLE
Optimization: Cards pool

### ISSUE THREAD

**Issue by WhimsySoftware** [EnigmaDragons/ProjectNeon#214]
Now cards are destroyed when switching between screens. Need to do a card pool and just change card state, but not destroy it each time.

**Comment by SilasReinagel** [comment]
Estimate: 2 units

**Comment by WhimsySoftware** [comment]
In order to complete this task, I must do the following:
1) Make the UpdateCurrentCards method in the CardsVisualizer.cs
2) Make the UpdateCurrentCards method in the DeckVisualizer.cs
3) Change the interaction between CardsVisualizers (there are at least two of them on the stage and they individually spawn their cards. Because of this, extra cards appear and the necessary ones are destroyed)
4) Change the interaction between CardsVisualizer and DeckVisualizer
I am not sure that individually these edits will work. I made the first edit in CardsVisualizer, but due to the fact that there are no other three, there is confusion and errors. Because of it i didn't push it to the repo.

@SilasReinagel

**Comment by SilasReinagel** [comment]
@WhimsySoftware You can create tickets for the work you think we will need.

1) We just need to tweak this one slightly, to use pooled cards instead of instantiating. I figured that's what this ticket would cover.

2) `DeckVisualizer` only displays summary items. It can use its own pool if needed, but that doesn't seem to be related to this work.

3) Yes. All Visualizers can use the same instance of a single Card pool. It can even be a `ScriptableObject` to ensure single shared state.

4) I don't see any reason why `CardsVisualizer`, which is used in `BattleScene`, needs to talk to `DeckVisualizer`, which lives in `DeckBuilderScene`. 

So, we only need to do #1 and #3, and both are quite trivial, yes?
